rules:
  default:
    protection: 0
      required_status_checks: 0
        contexts:
          - continuous-integration/travis-ci
      required_pull_request_reviews:
        required_approving_review_count: 0
  branches:
    protection: 0 
      stable/.*:
        required_pull_request_reviews: 0
          required_approving_review_count: 0
